version: '3'
services:
    awsdemo:
        build: .
        command: 'node app.js'
        volumes:
            - .:/usr/app/
            - /usr/app/node_modules
        ports:
            - '8080:8080'
        environment:
            - NODE_ENV=production
        depends_on:
            - couchdb
    couchdb:
        ports:
            - '5984:5984'
